FORMAT: 1A
HOST: https://url.leanapp.cn/

# Reducio

[Reducio](https://github.com/leeyeh/reducio) is a URL shortening service designed to be deployed on [LeanEngine](https://leancloud.cn/docs/leanengine_overview.html).

[![](https://developer.chrome.com/webstore/images/ChromeWebStore_BadgeWBorder_v2_206x58.png)](https://chrome.google.com/webstore/detail/jclafgekedbnphekfjeoalmlkiohikac)
[![](https://addons.cdn.mozilla.net/static/img/addons-buttons/AMO-button_1.png)](https://addons.mozilla.org/en-US/firefox/addon/reducio/)

## {HOST}/ [/]

### Create a shortened URL [POST]

+ Request (application/json)

        {
            "original": "https://leancloud.cn"
        }

+ Response 200 (application/json)

        {
            "short": "gaWegTm"
        }

## {HOST}/short_path [/{short_path}]

### Customize a shortened URL [PUT]

+ Parameters
    + short_path (string) - [0-9a-zA-z]+


+ Request (application/json)

        {
            "original": "https://leancloud.cn"
        }

+ Response 200 (application/json)

        {
            "short": "LC"
        }
